version: "3.9"

services:
  markey.api-gateway:
    container_name: markey.api-gateway
    build:
      context: .
    restart: unless-stopped
    ports:
      - "5050:8000"
    env_file:
      - .docker.env
    networks:
      - markey-backend-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 300M

networks:
  markey-backend-network:
    external: true
