export enum PostCategoryEnum {
  ADVERTISEMENT = 'ADVERTISEMENT',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  ARTICLE = 'ARTICLE',
  NEWS = 'NEWS',
  PROMOTION = 'PROMOTION',
  TUTORIAL = 'TUTORIAL',
  OTHER = 'OTHER'
}
