version: "3.9"

services:
  markey.order-service:
    container_name: markey.order-service
    build:
      context: ./main
    restart: unless-stopped
    ports:
      - "5002:4000"
    env_file:
      - .docker.env
    networks:
      - markey-backend-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 300M

networks:
  markey-backend-network:
    external: true
