name: Markey BACKEND CD Pipeline

env:
  PAYMENT_SERVICE_FOLDER: /root/markey_project/backend/markey.payment-service
  ORDER_SERVICE_FOLDER: /root/markey_project/backend/markey.order-service
  SHOPPING_SERVICE_FOLDER: /root/markey_project/backend/markey.shopping-service
  USER_SERVICE_FOLDER: /root/markey_project/backend/markey.user-service
  ENV_FOLDER: /root/markey_project/env_file/backend
  PROJECT_FOLDER: /root/markey_project/backend

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy source code to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.MARKEY_BACKEND_SERVER_HOST }}
          username: ${{ secrets.MARKEY_BACKEND_SERVER_USER }}
          password: ${{ secrets.MARKEY_BACKEND_SERVER_PASSWORD }}
          source: "./*"
          target: ${{ env.PROJECT_FOLDER }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.MARKEY_BACKEND_SERVER_HOST }}
          username: ${{ secrets.MARKEY_BACKEND_SERVER_USER }}
          password: ${{ secrets.MARKEY_BACKEND_SERVER_PASSWORD }}
          port: 22
          script: |
            cp ${{ env.ENV_FOLDER }}/payment-service.docker.env ${{ env.PAYMENT_SERVICE_FOLDER }}/main/.docker.env
            cp ${{ env.ENV_FOLDER }}/order-service.docker.env ${{ env.ORDER_SERVICE_FOLDER }}/main/.docker.env
            cp ${{ env.ENV_FOLDER }}/user-service.docker.env ${{ env.USER_SERVICE_FOLDER }}/main/.docker.env
            cp ${{ env.ENV_FOLDER }}/shopping-service.docker.env ${{ env.SHOPPING_SERVICE_FOLDER }}/main/.docker.env


            cd ${{ env.PROJECT_FOLDER }}
            sudo chmod +x docker-compose.down-all.sh    
            sudo chmod +x docker-compose.up-all.sh    

            ./docker-compose.down-all.sh
            ./docker-compose.up-all.sh
